In [1]:
import pandas as pd
df = pd.read_excel("total_25_final.xlsx")

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84102 entries, 0 to 84101
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   num              84102 non-null  int64
 1   region           84102 non-null  object
 2   title            84102 non-null  object
 3   category         84102 non-null  object
 4   time             84102 non-null  object
 5   price            84102 non-null  int64
 6   detail           83922 non-null  object
 7   interest         84102 non-null  int64
 8   chat             84102 non-null  int64
 9   view             84102 non-null  int64
 10  upload_datetime  84102 non-null  datetime64[ns]
 11  upload_date      84102 non-null  datetime64[ns]
 12  upload_ym        84102 non-null  object
 13  reup             84102 non-null  int64
 14  region_gu        84102 non-null  object
dtypes: datetime64[ns](2), int64(6), object(7)
memory usage: 9.6+ MB

In [5]:
df.shape

(84102, 15)

In [12]:
df.groupby('upload_ym').title.count()

upload_ym
2020-09    11065
2020-10     3053
2020-11     3854
2020-12     5054
2021-01     9875
2021-02     5875
2021-03     4643
2021-04     4499
2021-05     4077
2021-06     3945
2021-07     4406
2021-08     2786
2021-09    20970
Name: title, dtype: int64

In [12]:
df2 = pd.read_excel("df_token_2.xlsx")

In [18]:
df3 = df2[['num', 'title', 'time', 'price', 'detail', 'interest', 'chat', 'view', 'upload_datetime', 'upload_date', 'upload_ym', 'reup', 'region_gu', 'token', 'cate_final' ]]

In [27]:
df3.sample(3)

,num,title,time,price,detail,interest,chat,view,upload_datetime,upload_date,upload_ym,reup,region_gu,token,cate_final
156,263935543,설화수 자음2종 퍼펙팅 선물세트 (선물가능),끌올 1달 전,79000,\n선물받았는데\n화장품은 사용하는게 있어서 \n당근에 올립니다,10,2,234,2021-08-30 23:59:59,2021-08-30,2021-08,1,강남구,"['설화수', '자음2종']",cosmetics
28789,288220842,동원 참치 10호 세트 팔아용,11일 전,35000,참치랑 햄을안먹어서 선물세트팔아용,5,0,159,2021-09-19 22:47:26,2021-09-19,2021-09,0,동대문구,"['동원', '참치']",tuna
33091,179997768,화장품,8달 전,60000,입생로랑 엉크르 드 뽀 쿠션&틴트 세트 \n(엉크르 드 뽀 쿠션 SPF 25 &...,0,3,78,2021-01-30 23:59:59,2021-01-30,2021-01,0,마포구,['화장품'],cosmetics

In [33]:
df2[['title', 'token', 'cate_final']].sample(10)

                               title            token cate_final
40426            록시땅 선물세트 리퀴드 솝🔥마지막🔥          ['록시땅']       bath
48386                    미키하우스 커피잔세트        ['커피잔세트']     coffee
56962           cj 특별한선택 T호 선물세트 미개봉  ['cj', '특별한선택']        mix
23521                        작은 참기름병          ['참기름']        oil
13323              지오마 바디스크럽+로션 선물세트  ['로션', '바디스크럽']       bath
28495                      미사용 골프캐디백    ['골프', '캐디백']    leisure
52225  [정품][새제품] 버버리 카드&주사위 세트(선물가능)          ['버버리']     luxury
36008     일화 홍삼 석류 프리미엄 선물세트 미개봉 새상품           ['홍삼']    ginseng
35418                        해표 선물셋트           ['해표']        mix
6178                 젠한국 다기세트 새것 선물용         ['다기세트']     dishes

In [40]:
conditions = (df.upload_ym =='2021-09') | (df.upload_ym =='2021-01') | (df.upload_ym =='2020-09')
df[conditions].groupby('cate_final').title.count().sort_values(ascending=False)

cate_final
mix              5236
spam             3277
cosmetics        2911
dishes           2803
bath             2210
baby             1868
perfume          1667
tuna             1633
kitchen          1557
coffee           1493
hand             1376
cloth            1084
bath_thanks      1028
ginseng           989
fruits            897
jewel             520
oil               476
man               378
electric          336
leisure           286
meat              285
dried_seafood     244
snacks            222
spicy             216
nuts              213
luxury            182
furnishing        157
nutri             104
drink              89
hygiene            72
coupon             42
Name: title, dtype: int64

In [41]:
conditions = (df.upload_ym =='2021-09') | (df.upload_ym =='2021-01') | (df.upload_ym =='2020-09')
df[~conditions].groupby('cate_final').title.count().sort_values(ascending=False)

cate_final
dishes           4080
cosmetics        4027
baby             3226
bath             2842
perfume          2750
kitchen          2269
hand             2137
mix              1802
cloth            1729
coffee           1695
spam             1104
jewel             919
electric          656
man               574
ginseng           520
tuna              486
leisure           455
bath_thanks       440
oil               293
luxury            255
furnishing        249
spicy             160
fruits            158
nutri             152
snacks            130
coupon            112
hygiene           102
drink              97
nuts               67
meat               53
dried_seafood      31
Name: title, dtype: int64

In [42]:
df.groupby('cate_final').title.count().sort_values(ascending=False)

cate_final
mix              7038
cosmetics        6938
dishes           6883
baby             5094
bath             5052
perfume          4417
spam             4381
kitchen          3826
hand             3513
coffee           3188
cloth            2813
tuna             2119
ginseng          1509
bath_thanks      1468
jewel            1439
fruits           1055
electric          992
man               952
oil               769
leisure           741
luxury            437
furnishing        406
spicy             376
snacks            352
meat              338
nuts              280
dried_seafood     275
nutri             256
drink             186
hygiene           174
coupon            154
Name: title, dtype: int64

In [44]:
sth = pd.read_excel('df_token_final_sth.xlsx')

In [45]:
sth

,num,region,title,category,time,price,detail,interest,chat,view,upload_datetime,upload_date,upload_ym,reup,region_gu,token,token_sum,cate_temp,cate_final,token_final
0,259532636,강남구 도곡2동,<이민정리/미개봉 새제품> 뚜아엘 핸드마스크 8매 + 틴케이스 세트,뷰티/미용,3달 전,29000,"정가 80000원, 2022년 4월까지인 핸드마스크 세트입니다. 쇼핑백도 함께 드리...",0,0,53,2021-06-30 23:59:59,2021-06-30,2021-06,0,강남구,"['마스크', '핸드']",마스크 핸드,"['hand', 'hygiene']",hand,핸드크림
1,287768851,강남구 도곡동,동원 참치 프리미엄선물세트,생활/가공식품,12일 전,22000,어제 받은 추석선물 입니다!\n참치를 안좋아해서요…\n선물 케이스 그대로 드립니다!...,3,1,199,2021-09-18 23:59:59,2021-09-18,2021-09,0,강남구,"['동원', '참치']",동원 참치,['tuna'],tuna,동원참치
2,156510279,강남구 대치동,"(새 제품) 더프트 앤 도프트 핸드크림, 틴케이스 세트",뷰티/미용,끌올 8달 전,10000,25mL 핸드크림 3개 + 틴케이스 선물세트 입니다~,1,1,126,2021-01-30 23:59:59,2021-01-30,2021-01,1,강남구,['핸드크림'],핸드크림,['hand'],hand,핸드크림
3,280382837,강남구 자곡동,템버린즈 손소독제 세트 선물포장제품,뷰티/미용,끌올 26일 전,18000,27000원에 구매했습니당 저렴하게 팔아요,0,2,46,2021-09-04 23:59:59,2021-09-04,2021-09,1,강남구,['손소독제'],손소독제,['hand'],hand,기타
4,160658769,강남구 자곡동,스팸 선물세트(미개봉),생활/가공식품,끌올 9달 전,19000,스팸선물세트 미개봉입니다.\n스팸 클래식 200g *7개\n카놀라유 500ml * ...,2,3,210,2020-12-30 23:59:59,2020-12-30,2020-12,1,강남구,['스팸'],스팸,['spam'],spam,스팸
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10008,264597174,중랑구 신내동,동원 선물세트,생활/가공식품,2달 전,20000,유통기한\n참치 27년까지\n햄 23년까지\n환불불가\n가지러 오셔야 합니다.\n서...,4,1,143,2021-07-30 23:01:15,2021-07-30,2021-07,0,중랑구,['동원'],동원,['tuna'],tuna,동원참치
10009,192114530,중랑구 면목본동,스팸복합1호 선물셋트,생활/가공식품,8달 전,13000,선물받은거 안써서 내놔요.,5,4,898,2021-01-30 23:01:15,2021-01-30,2021-01,0,중랑구,['스팸복합1호'],스팸복합1호,['spam'],spam,스팸
10010,164736659,중랑구 상봉제1동,스팸 12호 선물세트 팝니다.,생활/가공식품,10달 전,16000,스팸 12호 선물세트 팝니다. \n200g x 8개 입니다.\n새제품 이고 유통기한...,1,2,159,2020-11-30 23:01:15,2020-11-30,2020-11,0,중랑구,['스팸'],스팸,['spam'],spam,스팸
10011,292385197,중랑구 묵제1동,스팸 마일드 8호 미개봉,생활/가공식품,1일 전,19000,스팸 선물세트 미개봉 팝니다\n직거래 선호합니다,6,0,109,2021-09-29 23:01:15,2021-09-29,2021-09,0,중랑구,['스팸'],스팸,['spam'],spam,스팸
10012,275017997,중랑구 면목본동,캐스키드슨 바디미스트&핸드크림 세트,뷰티/미용,끌올 30일 전,7000,카카오톡 선물로 받았는데 안 쓸것 같아 판매합니다!\n이제 곧 가을인데 핸드크림이랑...,1,0,37,2021-08-31 23:01:15,2021-08-31,2021-08,1,중랑구,"['바디미스트', '캐스키드슨', '핸드크림']",바디미스트 캐스키드슨 핸드크림,"['bath', 'hand']",hand,캐스키드슨

In [49]:
sth.groupby(['cate_final', 'token_final']).title.count()

cate_final  token_final
hand        기타               33
            더프트앤도프트          72
            랩신               53
            록시땅            1224
            비욘드              41
            시어버터            123
            이솝              185
            카밀               56
            캐스키드슨           209
            키엘               43
            탬버린즈            108
            프레쉬             135
            핸드크림           1231
spam        그릭슈바인            62
            런천미트             67
            로스팜             232
            리챔              236
            수제햄              38
            스팸             3555
            햄               151
tuna        동원참치           1844
            사조참치            102
            참치선물세트          170
Name: title, dtype: int64

In [10]:
df = df[df.detail.apply(lambda x :len(str(x))) > 0]

In [18]:
df[df.detail.str.contains('문고리',na=False) ][['detail']]

                                                  detail
1267            선물 받았는데 저희집 그릇이랑 안 어울리네요\n비대면 문고리 거래 합니다
7403   아토팜 엠엘이크림 미개봉 새상품입니다\n100ml 2개입 기획세트로 제조일자 20년...
7414   새제품입니다.  \n교환, 환불은 어려운 점 이해 부탁드려요~ \n신암초 인근 직거...
7558   이번에 들어온 선물세트인데 안먹어서 바로 내놓음\n쇼핑백 없지만 현대백화점 봉투에 ...
7707   네이버 최저가 37000원 정도에 판매되는 상품 입니다\n스팸 120g 6개,  2...
...                                                  ...
78738  그릭슈바인 선물세트 팝니다\n스팸보다 고급지고\n포장도 멋짐\n유통기한. 구성품 기...
79195                           새상품 어제배송받았어요\n녹번 문고리거래해요
81025  커피 선물세트에 들어있던 컵인데\n사용하지 않을것같아 내놓아요~\n비대면 문고리거래...
82587  첨부와 같이 선물세트 (샴푸,치약,비누) 2세트 있습니다.\n쿨거래시 2세트 일괄 ...
82887  안녕하세요~\n미엘드 벌꿀 선물세트 새상품 판매합니다.\n선물용으로 아주 좋을 것 ...

[109 rows x 1 columns]

In [19]:
df2[df2['detail'].str.contains('문고리', na=False)]

,num,region,title,category,time,price,detail,interest,chat,view,upload_datetime,upload_date,upload_ym,reup,region_gu,token,token_sum,cate_temp,cate_final
1015,172119195,강남구 개포동,이도 도자기 찻잔 커피잔 2P 선물세트,생활/가공식품,9달 전,29000,선물 받았는데 저희집 그릇이랑 안 어울리네요\n비대면 문고리 거래 합니다,0,1,150,2020-12-30 23:59:59,2020-12-30,2020-12,0,강남구,"['도자기', '찻잔', '커피잔']",도자기 찻잔 커피잔,['dishes'],dishes
5887,259333716,강동구 명일동,아토팜 MLE크림 2개입 기획세트(미개봉새상품),유아동,3달 전,18000,아토팜 엠엘이크림 미개봉 새상품입니다\n100ml 2개입 기획세트로 제조일자 20년...,3,1,38,2021-06-30 23:59:59,2021-06-30,2021-06,0,강동구,"['아토팜', '크림']",아토팜 크림,"['baby', 'cosmetics']",cosmetics
5893,284951005,강동구 암사동,동원참치 리챔 선물세트 (명품혼합 V10호),생활/가공식품,19일 전,30000,"새제품입니다. \n교환, 환불은 어려운 점 이해 부탁드려요~ \n신암초 인근 직거...",1,1,135,2021-09-11 23:59:59,2021-09-11,2021-09,0,강동구,"['동원참치', '리챔']",동원참치 리챔,"['spam', 'tuna']",mix
6008,286825428,강동구 고덕동,미개봉 스팸세트,생활/가공식품,끌올 12일 전,33000,이번에 들어온 선물세트인데 안먹어서 바로 내놓음\n쇼핑백 없지만 현대백화점 봉투에 ...,6,4,410,2021-09-18 23:59:59,2021-09-18,2021-09,1,강동구,['스팸세트'],스팸세트,['spam'],spam
6126,288033274,강동구 고덕제1동,스팸 선물세트,생활/가공식품,12일 전,20000,"네이버 최저가 37000원 정도에 판매되는 상품 입니다\n스팸 120g 6개, 2...",1,1,156,2021-09-18 23:59:59,2021-09-18,2021-09,0,강동구,['스팸'],스팸,['spam'],spam
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63155,281223135,은평구 불광동,그릭슈바인 선물세트 겉포장지 있음,생활/가공식품,끌올 23일 전,8000,그릭슈바인 선물세트 팝니다\n스팸보다 고급지고\n포장도 멋짐\n유통기한. 구성품 기...,0,2,169,2021-09-07 23:27:55,2021-09-07,2021-09,1,은평구,['그릭슈바인'],그릭슈바인,['spam'],spam
63515,275618627,은평구 응암제1동,르네휘테르 샴푸+세럼 선물세트,뷰티/미용,끌올 1달 전,33000,새상품 어제배송받았어요\n녹번 문고리거래해요,2,1,43,2021-08-30 23:27:55,2021-08-30,2021-08,1,은평구,"['샴푸', '세럼']",샴푸 세럼,"['bath', 'cosmetics']",cosmetics
64988,193583986,중구 문화동,투썸플레이스 머그컵 4개,생활/가공식품,8달 전,10000,커피 선물세트에 들어있던 컵인데\n사용하지 않을것같아 내놓아요~\n비대면 문고리거래...,0,1,133,2021-01-30 21:53:21,2021-01-30,2021-01,0,중구,"['머그컵', '투썸플레이스']",머그컵 투썸플레이스,"['coffee', 'dishes']",dishes
66222,249899370,중랑구 면목본동,"LG생활건강 선물세트 샴푸,치약,비누 (새상품)",뷰티/미용,3달 전,8000,"첨부와 같이 선물세트 (샴푸,치약,비누) 2세트 있습니다.\n쿨거래시 2세트 일괄 ...",2,1,107,2021-06-30 23:01:15,2021-06-30,2021-06,0,중랑구,"['lg생활건강', '비누', '샴푸', '치약']",lg생활건강 비누 샴푸 치약,"['bath', 'bath_thanks']",bath_thanks
66465,291377479,중랑구 묵동,미엘드 벌꿀 선물세트 새상품,생활/가공식품,끌올 1일 전,27000,안녕하세요~\n미엘드 벌꿀 선물세트 새상품 판매합니다.\n선물용으로 아주 좋을 것 ...,2,0,184,2021-09-29 23:01:15,2021-09-29,2021-09,1,중랑구,"['미엘드', '벌꿀']",미엘드 벌꿀,['spicy'],spicy